export const data = [
  {
    id: 1,
    coverimg: "swimmer.png",
    stats: {
      rating: "5.0",
      reviewcount: 6,
    },
    title: "Life Lessons with Katie Zaferes",
    description: "Katie Zaferes smiling poolside",
    price: 136,
    location: "USA",
    openspots: 0,
  },
  {
    id: 2,
    coverimg: "wedding.png",
    stats: {
      rating: "5.0",
      reviewcount: 30,
    },
    title: "Learn wedding photography",
    description: "Bride to be in wedding dress",
    price: 125,
    location: "Online",
    openspots: 27,
  },
  {
    id: 3,
    coverimg: "mountain.png",
    stats: {
      rating: "4.8",
      reviewcount: 2,
    },
    title: "Group Mountain Biking",
    description: "Mountain bike in the mountains",
    price: 50,
    location: "Norway",
    openspots: 3,
  },
  {
    id: 1,
    coverimg: "swimmer.png",
    stats: {
      rating: "5.0",
      reviewcount: 6,
    },
    title: "Life Lessons with Katie Zaferes",
    description: "Katie Zaferes smiling poolside",
    price: 136,
    location: "USA",
    openspots: 0,
  },
  {
    id: 2,
    coverimg: "wedding.png",
    stats: {
      rating: "5.0",
      reviewcount: 30,
    },
    title: "Learn wedding photography",
    description: "Bride to be in wedding dress",
    price: 125,
    location: "Online",
    openspots: 27,
  },
  {
    id: 3,
    coverimg: "mountain.png",
    stats: {
      rating: "4.8",
      reviewcount: 2,
    },
    title: "Group Mountain Biking",
    description: "Mountain bike in the mountains",
    price: 50,
    location: "Norway",
    openspots: 3,
  },
  {
    id: 1,
    coverimg: "swimmer.png",
    stats: {
      rating: "5.0",
      reviewcount: 6,
    },
    title: "Life Lessons with Katie Zaferes",
    description: "Katie Zaferes smiling poolside",
    price: 136,
    location: "USA",
    openspots: 0,
  },
  {
    id: 2,
    coverimg: "wedding.png",
    stats: {
      rating: "5.0",
      reviewcount: 30,
    },
    title: "Learn wedding photography",
    description: "Bride to be in wedding dress",
    price: 125,
    location: "Online",
    openspots: 27,
  },
  {
    id: 3,
    coverimg: "mountain.png",
    stats: {
      rating: "4.8",
      reviewcount: 2,
    },
    title: "Group Mountain Biking",
    description: "Mountain bike in the mountains",
    price: 50,
    location: "Norway",
    openspots: 3,
  },
];
